# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 01:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_file', models.CharField(default='xml file', max_length=40, unique=1)),
                ('xml_files', models.FileField(upload_to='upload_xml_files')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='upload_groups',
            fields=[
                ('upload_group', models.CharField(max_length=40)),
                ('upload_substrate', models.CharField(blank=True, default='', max_length=40)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='xml_intensities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intensities', models.TextField()),
                ('startPosition', models.FloatField(default=None)),
                ('endPosition', models.FloatField(default=None)),
                ('upload_xml', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='uploading_data.upload')),
            ],
        ),
        migrations.AddField(
            model_name='upload',
            name='file_upl_group',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='uploading_data.upload_groups'),
        ),
    ]
