# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 04:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uploading_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_growth', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='xml_intensities',
            name='ext_training',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='uploading_data.training'),
        ),
    ]
