# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-25 02:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uploading_data.models


class Migration(migrations.Migration):

    dependencies = [
        ('uploading_data', '0005_auto_20170724_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='file_upl_group',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='uploading_data.upload_groups', validators=[uploading_data.models.validate_group]),
        ),
    ]
