# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 00:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='info_main',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_1', models.ImageField(default='static/information/img/lab.jpg', upload_to='pic_folder/')),
                ('image_2', models.ImageField(default='static/information/img/lab.jpg', upload_to='pic_folder/')),
                ('block_1', models.TextField(blank=True, default='')),
                ('block_2', models.TextField(blank=True, default='')),
            ],
        ),
    ]
